title:         Project

files:
  sortable:    true

pages:         false

icon:          folder-open-o

fields:
  title:
    label:     Title
    type:      text
    width:     2/5

  subtitle:
    label:     Subtitle
    type:      text
    width:     2/5

  year:
    label:     Year
    type:      text
    width:     1/5

  text:
    label:     Text
    type:      markdown

  coverimage:
    label:     coverimage
    type:      image
